export const SET_SEARCH_STRING = "SET_SEARCH_STRING";
export const ADD_ALL_GENRES = "ADD_ALL_GENRES";
export const ADD_RECOMENDATIONS = "ADD_RECOMENDATIONS";
export const ADD_MOVIE_DETAILS = "ADD_MOVIE_DETAILS";
